image: rust:latest

pages:
  script:
    - cargo install mdbook --vers 0.4.52
    - python3 scripts/generate_summary.py
    - mdbook build
    - mv book public
  artifacts:
    paths:
      - public
  only:
    - main
