[book]
authors = ["c4m1r"]
language = "en"
multilingual = false
src = "src"
title = "C4m1r's wiki"


[output.html]
theme = "theme"
default-theme = "dark"
preferred-dark-theme = "dark"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/c4m1r/wiki"
git-repository-icon = "fa-github"
site-url = "/wiki/"
additional-js = ["js/search.js", "js/ticker.js", "js/counter.js"]
additional-css = ["css/custom.css"]

[output.html.search]
enable = false
