[book]
authors = ["c4m1r"]
language = "ru"
multilingual = true
src = "src"
title = "C4m1r's wiki"


[output.html]
theme = "src/theme"
default-theme = "dark"
preferred-dark-theme = "dark"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/c4m1r/wiki"
git-repository-icon = "fa-github"
site-url = "/wiki/"
additional-js = ["src/js/search.js", "src/js/ticker.js", "src/js/counter.js", "src/js/language-switcher.js"]
additional-css = ["src/css/custom.css"]

[output.html.search]
enable = false
