[package]
name = "nervaweb"
version = "1.0.0"
edition = "2021"

[build]
target-dir = "../../target"

[[bin]]
name = "nervaweb"
path = "main.rs"

[dependencies]
regex = "1.10"
handlebars = "4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
